crud/urls.py
from django.urls import path
from . import views

app_name = "crud"

urlpatterns = [
	path("createInfo",views.CreateInfo.as_view(),name="createInfo"),
	path("infos",views.Infos.as_view(),name="infos"),
	path("info/<int:pk>",views.Info.as_view(),name="info"),
	path("editInfo/<int:pk>",views.EditInfo.as_view(),name="editInfo"),
	path("deleteInfo/<int:pk>",views.DeleteInfo.as_view(),name="deleteInfo"),
]

django_crud/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('crud.urls',namespace="curd")),
]

crud/models.py
from django.db import models

# Create your models here.
class Address(models.Model):
	country = models.CharField(max_length=50)
	state = models.CharField(max_length=50)
	city = models.CharField(max_length=50)
		
	def __str__(self) -> str:
		return f"{self.country},{self.state},{self.city}"

class Info(models.Model):
	firstName = models.CharField(max_length=25)
	middleName = models.CharField(max_length=25,blank=True)
	lastName = models.CharField(max_length=25)
	dob = models.DateField()
	address = models.ForeignKey(Address,null=True,blank=True,on_delete=models.SET_NULL,related_name="infos")
 
	def __str__(self) -> str:
		return f"{self.firstName} {self.middleName} {self.lastName}"

crud/forms.py
from django.forms import ModelForm
from . import models

class InfoForm(ModelForm):
    class Meta:
        model = models.Info
        fields = ['firstName', 'middleName', 'lastName', 'dob', 'address']

crud/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models,forms

class CreateInfo(CreateView):
    context_object_name = "info"
    model = models.Info
    form_class = forms.InfoForm
    template_name = "createInfo.html"
    success_url = reverse_lazy("crud:infos")

class Infos(ListView):
    allow_empty = True
    context_object_name = "infos"
    model = models.Info
    template_name = "infos.html"

class Info(DetailView):
    context_object_name = "info"
    model = models.Info
    template_name = "info.html"

class EditInfo(UpdateView):
    context_object_name = "info"
    model = models.Info
    form_class = forms.InfoForm
    template_name = "updateInfo.html"
    success_url = reverse_lazy("crud:infos")

class DeleteInfo(DeleteView):
    context_object_name = "info"
    model = models.Info
    template_name = "deleteInfo.html"
    success_url = reverse_lazy("crud:infos")

templates/createInfo.html
<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit">Create</button>
</form>

templates/deleteInfo.html
<form method="post">
	{% csrf_token %}
	<p>Are you sure you want to delete {{ info }}?</p>
	<button type="submit">Delete</button>
</form>

templates/info.html
<h1>firstName</h1>
<p> {{info.firstName}} </p>
<h1>middleName</h1>
<p> {{info.middleName}} </p>
<h1>lastName</h1>
<p> {{info.lastName}} </p>
<h1>dob</h1>
<p> {{info.dob}} </p>
<h1>address</h1>
<p> {{info.address.city}},{{info.address.state}},{{info.address.city}} </p>


<a href="{% url 'crud:editInfo' info.pk %}"><button>Edit</button></a>
<a href="{% url 'crud:deleteInfo' info.pk %}"><button>Delete</button></a>

templates/infos.html
<a href="{% url 'crud:createInfo' %}"><button>Create</button></a>
{% for info in infos %}
<a href="{% url 'crud:info' info.pk %}"><h1>{{info}}</h1></a>
{% endfor %}

templates/updateInfo.html
<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit">Create</button>
</form>